### ISSUE TITLE
Lower CPU usage

### ISSUE THREAD

**Issue by gurghet** [laserdisc-io/tamer#246]
@barambani noticed with S3 module tamer uses 100% cpu.
I suspect because of
https://github.com/laserdisc-io/tamer/blob/2fff351e57f6abc86f0e2ba27e4c863e39d1fb55/core/src/main/scala/tamer/kafka/Kafka.scala#L126
More evidence comes from dumping the fibers in a random moment:
```
#64 (14m871s871268ms) 
   Status: Running()
Fiber:Id(1613749779114,64) was supposed to continue to:
  a future continuation at zio.ZIO.forever(ZIO.scala:686)

Fiber:Id(1613749779114,64) execution trace:
  at zio.ZIO.forever(ZIO.scala:686)
  at zio.ZIO.unit(ZIO.scala:2014)
  at log.effect.LogWriterConstructor$$anon$1$$anon$2.write(LogWriterConstructor.scala:31)
  at tamer.kafka.Kafka$$anon$1.runLoop(Kafka.scala:66)
  at zio.ZQueue$$anon$4.takeAll(ZQueue.scala:627)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2662)
  ...
```
Do you think this is the problem?
Should we solve it by using `take`, which suspends, instead of `takeAll` that continuously returning an empty list?

**Comment by barambani** [comment]
As discussed offline, let's try take.
